genericSpecificURLnav/urls.py
from django.contrib import admin
from django.urls import path, include

from rapido.views import *
from zomato.views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path('auto/', auto, name='auto'),
    path('biriyani/', biriyani, name='biriyani'),
    path('rapido/', include('rapido.urls')),
    path('zomato/', include('zomato.urls')),
]

rapido/urls.py
from django.urls import path
from rapido.views import *
app_name = 'rapido'

urlpatterns = [
    path('auto/', auto, name='auto')
]

zomato/urls.py
from django.urls import path
from zomato.views import *
app_name = 'zomato'

urlpatterns = [
    path('biriyani/', biriyani, name='biriyani')
]

rapido/models.py
from django.db import models

# Create your models here.

zomato/models.py
from django.db import models

# Create your models here.

rapido/views.py
from django.shortcuts import render

# Create your views here.
def auto(request):
    return render(request, 'auto.html')

zomato/views.py
from django.shortcuts import render

# Create your views here.
def biriyani(request):
    return render(request, 'biriyani.html')

templates/auto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        a{
            text-decoration: none;
            background-color: blueviolet;
            padding: 7px;
            color: white;
        }
    </style>
</head>
<body>
    <center>
        <!-- <h1>This is generic url navigation</h1>
        <a href="{% url 'biriyani' %}">Click here</a> -->

        <h1>This is specific url navigation</h1>
        <a href="{% url 'zomato:biriyani' %}">Click here</a>
    </center>
</body>
</html>

templates/biriyani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        a{
            text-decoration: none;
            background-color:brown;
            padding: 7px;
            color: white;
        }
    </style>
</head>
<body>
    <center>
        <!-- <h1>This is 2nd generic url navigation</h1>
        <a href="{% url 'auto' %}">Click here</a> -->

        <h1>This is 2nd specific url navigation</h1>
        <a href="{% url 'rapido:auto' %}">Click here</a>
    </center>
</body>
</html>